- hosts: host01
  become: true
  tasks:
    - name: Install Apache
      apt:
        pkg: ["apache2","git","libapache2-mod-php"]
        state: latest
        update_cache: true
    - name: push new vh
      copy:
        src: files/awesome-app
        dest: /etc/apache2/sites-available/awesome-app.conf
        mode: 640
    - name: disable default VH
      file:
        dest: /etc/apache2/sites-enabled/000-default.conf
        state: absent
      notify:
        - restart apache
    - name: disable default ssl
      file:
        dest: /etc/apache2/sites-enabled/default-ssl.conf
        state: absent
      notify:
        - restart apache
    - name: enable our new VH
      file:
        src: /etc/apache2/sites-available/awesome-app.conf
        dest: /etc/apache2/sites-enabled/awesome-app.conf
        state: link
      notify:
        - restart apache
    - name: install app
      git:
        repo: https://github.com/jwkidd3/ansible-tuto-demosite
        dest: /var/www/awesome-app
      tags: deploy
    - name: start apache
      service:
        name: apache2
        state: started
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
